### TRAINING THE HEALTH-MODEL:

In [1]:
#.......................................................Health_Training...............................................#

import os
import time
import joblib
import warnings
import numpy as np
import pandas as pd
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix  
from sklearn.metrics import classification_report 
warnings.filterwarnings(action = 'ignore')
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv("./dataset.csv")
df[:] = np.nan_to_num(df)

In [3]:
df[:]

Temperature  Pulse  O2  Result
0                84     63  96       0
1                96     94  90       1
2               100    100  94       2
3                85     62  96       0
4                97     99  99       1
...             ...    ...  ..     ...
149995           96     97  98       1
149996          101    101  93       2
149997           88     60  98       0
149998           95     90  95       1
149999          104    100  94       2

[150000 rows x 4 columns]

In [4]:
df = df.loc[:, ~df.columns.str.contains('^Unnamed')]
df

Temperature  Pulse  O2  Result
0                84     63  96       0
1                96     94  90       1
2               100    100  94       2
3                85     62  96       0
4                97     99  99       1
...             ...    ...  ..     ...
149995           96     97  98       1
149996          101    101  93       2
149997           88     60  98       0
149998           95     90  95       1
149999          104    100  94       2

[150000 rows x 4 columns]

In [5]:
df.shape

(150000, 4)

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150000 entries, 0 to 149999
Data columns (total 4 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Temperature  150000 non-null  int64
 1   Pulse        150000 non-null  int64
 2   O2           150000 non-null  int64
 3   Result       150000 non-null  int64
dtypes: int64(4)
memory usage: 4.6 MB


In [7]:
df.describe()

Temperature          Pulse             O2         Result
count  150000.000000  150000.000000  150000.000000  150000.000000
mean       94.673013      90.492953      95.159193       1.000000
std         5.757396      12.657377       3.002868       0.816499
min        84.000000      60.000000      90.000000       0.000000
25%        90.000000      83.000000      93.000000       0.000000
50%        95.000000      94.000000      95.000000       1.000000
75%        99.000000     100.000000      98.000000       2.000000
max       104.000000     105.000000     100.000000       2.000000

In [8]:
df.head(73590)

Temperature  Pulse  O2  Result
0               84     63  96       0
1               96     94  90       1
2              100    100  94       2
3               85     62  96       0
4               97     99  99       1
...            ...    ...  ..     ...
73585           93     96  92       1
73586          104     99  94       2
73587           87     66  97       0
73588           96     96  97       1
73589          102    105  94       2

[73590 rows x 4 columns]

In [9]:
y = df['Result'].values
X = df.drop('Result', axis=1).values

In [10]:
knn = KNeighborsClassifier(n_neighbors=6)

In [11]:
knn.fit(X,y)

KNeighborsClassifier(n_neighbors=6)

In [12]:
y_pred = knn.predict(X)
print("Prediction : {}".format(y_pred))

Prediction : [0 1 2 ... 0 1 2]


In [13]:
print("Health_Model Accuracy:",metrics.accuracy_score(y, y_pred)*100)

Health_Model Accuracy: 99.41266666666667


In [14]:
joblib.dump(knn,'Health_Model.pkl')

['Health_Model.pkl']

In [15]:
results = confusion_matrix(y, y_pred) 
print('Confusion Matrix :')
print(results) 
print('Accuracy Score :',accuracy_score(y, y_pred))
print('Report :')
print(classification_report(y, y_pred))

Confusion Matrix :
[[49841   159     0]
 [   51 49702   247]
 [    0   424 49576]]
Accuracy Score : 0.9941266666666667
Report :
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     50000
           1       0.99      0.99      0.99     50000
           2       1.00      0.99      0.99     50000

    accuracy                           0.99    150000
   macro avg       0.99      0.99      0.99    150000
weighted avg       0.99      0.99      0.99    150000

