### TRAINING THE PILLOW-MODEL:

In [1]:
#................................................Pillow-Training.....................................................#

import os
import time
import joblib
import warnings
import numpy as np
import pandas as pd
from sklearn import metrics
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix  
from sklearn.metrics import classification_report 
warnings.filterwarnings(action = 'ignore')
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split

C:\Users\sumit\anaconda3\lib\site-packages\numpy\_distributor_init.py:32: UserWarning: loaded more than 1 DLL from .libs:
C:\Users\sumit\anaconda3\lib\site-packages\numpy\.libs\libopenblas.PYQHXLVVQ7VESDPUVUADXEVJOBGHJPAY.gfortran-win_amd64.dll
C:\Users\sumit\anaconda3\lib\site-packages\numpy\.libs\libopenblas.XWYDX2IKJW2NMTWSFYNGFUWKQU3LYTCZ.gfortran-win_amd64.dll
  stacklevel=1)


In [2]:
df = pd.read_csv("./PILLOW_DATASET/HeartBeat.csv")

In [5]:
df

Heart_Beat  Left_Sleep  Mid_Sleep  Right_Sleep            Result
0               0           1          0            0  Danger-LeftSleep
1               1           1          0            0  Danger-LeftSleep
2               2           1          0            0  Danger-LeftSleep
3               3           1          0            0  Danger-LeftSleep
4               4           1          0            0  Danger-LeftSleep
...           ...         ...        ...          ...               ...
67945         146           0          0          150  Snore-RightSleep
67946         147           0          0          150  Snore-RightSleep
67947         148           0          0          150  Snore-RightSleep
67948         149           0          0          150  Snore-RightSleep
67949         150           0          0          150  Snore-RightSleep

[67950 rows x 5 columns]

In [6]:
df.shape

(67950, 5)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 67950 entries, 0 to 67949
Data columns (total 5 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   Heart_Beat   67950 non-null  int64 
 1   Left_Sleep   67950 non-null  int64 
 2   Mid_Sleep    67950 non-null  int64 
 3   Right_Sleep  67950 non-null  int64 
 4   Result       67950 non-null  object
dtypes: int64(4), object(1)
memory usage: 2.6+ MB


In [8]:
df.describe()

Heart_Beat    Left_Sleep     Mid_Sleep   Right_Sleep
count  67950.00000  67950.000000  67950.000000  67950.000000
mean      75.00000     25.166681     25.166681     25.166681
std       43.58931     43.493960     43.493960     43.493960
min        0.00000      0.000000      0.000000      0.000000
25%       37.00000      0.000000      0.000000      0.000000
50%       75.00000      0.000000      0.000000      0.000000
75%      113.00000     38.000000     38.000000     38.000000
max      150.00000    150.000000    150.000000    150.000000

In [9]:
df#.head(10)

Heart_Beat  Left_Sleep  Mid_Sleep  Right_Sleep            Result
0               0           1          0            0  Danger-LeftSleep
1               1           1          0            0  Danger-LeftSleep
2               2           1          0            0  Danger-LeftSleep
3               3           1          0            0  Danger-LeftSleep
4               4           1          0            0  Danger-LeftSleep
...           ...         ...        ...          ...               ...
67945         146           0          0          150  Snore-RightSleep
67946         147           0          0          150  Snore-RightSleep
67947         148           0          0          150  Snore-RightSleep
67948         149           0          0          150  Snore-RightSleep
67949         150           0          0          150  Snore-RightSleep

[67950 rows x 5 columns]

In [10]:
y = df['Result'].values
X = df.drop('Result', axis=1).values

In [11]:
X

array([[  0,   1,   0,   0],
       [  1,   1,   0,   0],
       [  2,   1,   0,   0],
       ...,
       [148,   0,   0, 150],
       [149,   0,   0, 150],
       [150,   0,   0, 150]], dtype=int64)

In [12]:
y

array(['Danger-LeftSleep', 'Danger-LeftSleep', 'Danger-LeftSleep', ...,
       'Snore-RightSleep', 'Snore-RightSleep', 'Snore-RightSleep'],
      dtype=object)

In [13]:
knn = KNeighborsClassifier(n_neighbors=6)

In [14]:
knn.fit(X,y)

KNeighborsClassifier(n_neighbors=6)

In [15]:
y_pred = knn.predict(X)
print("Prediction : {}".format(y_pred))

Prediction : ['Danger-LeftSleep' 'Danger-LeftSleep' 'Danger-LeftSleep' ...
 'Snore-RightSleep' 'Snore-RightSleep' 'Snore-RightSleep']


In [16]:
print("Pillow_Model Accuracy:",metrics.accuracy_score(y, y_pred)*100)

Pillow_Model Accuracy: 100.0


In [17]:
joblib.dump(knn,'Pillow_model.pkl')

['Pillow_model.pkl']

In [18]:
results = confusion_matrix(y, y_pred) 
print('Confusion Matrix :')
print(results) 
print('Accuracy Score :',accuracy_score(y, y_pred))
print('Report :')
print(classification_report(y, y_pred))

Confusion Matrix :
[[9150    0    0    0    0    0    0    0    0]
 [   0 9150    0    0    0    0    0    0    0]
 [   0    0 9150    0    0    0    0    0    0]
 [   0    0    0 6000    0    0    0    0    0]
 [   0    0    0    0 6000    0    0    0    0]
 [   0    0    0    0    0 6000    0    0    0]
 [   0    0    0    0    0    0 7500    0    0]
 [   0    0    0    0    0    0    0 7500    0]
 [   0    0    0    0    0    0    0    0 7500]]
Accuracy Score : 1.0
Report :
                   precision    recall  f1-score   support

 Danger-LeftSleep       1.00      1.00      1.00      9150
  Danger-MidSleep       1.00      1.00      1.00      9150
Danger-RightSleep       1.00      1.00      1.00      9150
 Normal-LeftSleep       1.00      1.00      1.00      6000
  Normal-MidSleep       1.00      1.00      1.00      6000
Normal-RightSleep       1.00      1.00      1.00      6000
  Snore-LeftSleep       1.00      1.00      1.00      7500
   Snore-MidSleep       1.00      1.00      1